# Generated by Django 3.0.8 on 2020-07-19 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_auto_20200718_0925'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название показателя социального результата')),
                ('outcome_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Outcome')),
            ],
            options={
                'verbose_name': 'Показатель социального результата',
                'verbose_name_plural': 'Показатели социального результата',
            },
        ),
    ]
