# Generated by Django 3.0.8 on 2020-07-19 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0004_outcomemethod'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='outcomemethod',
            options={'verbose_name': 'Метод и инструмент сбора данных', 'verbose_name_plural': 'Методы и инструменты сбора данных'},
        ),
        migrations.AddField(
            model_name='outcome',
            name='method_refs',
            field=models.ManyToManyField(blank=True, to='public.OutcomeMethod', verbose_name='Методы и инструменты сбора данных'),
        ),
    ]
