# Generated by Django 2.0.2 on 2020-08-16 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0012_auto_20200812_0219'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringPlanLineImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Вопрос')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('method', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Метод')),
                ('tool', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Инструмент')),
                ('frequency', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Частота сбора')),
                ('reporting', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Отчетность и использование')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('result_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ProgramImpact', verbose_name='Результат')),
            ],
            options={
                'verbose_name_plural': 'Строки плана мониторинга для социального эффекта',
                'verbose_name': 'Строка плана мониторинга для социального эффекта',
            },
        ),
        migrations.CreateModel(
            name='MonitoringPlanLineMidOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Вопрос')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('method', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Метод')),
                ('tool', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Инструмент')),
                ('frequency', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Частота сбора')),
                ('reporting', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Отчетность и использование')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('result_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ProgramMidOutcome', verbose_name='Результат')),
            ],
            options={
                'verbose_name_plural': 'Строки плана мониторинга для среднесрочного социального результата',
                'verbose_name': 'Строка плана мониторинга для среднесрочного социального результата',
            },
        ),
        migrations.CreateModel(
            name='MonitoringPlanLineOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Вопрос')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('method', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Метод')),
                ('tool', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Инструмент')),
                ('frequency', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Частота сбора')),
                ('reporting', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Отчетность и использование')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('result_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ProgramOutput', verbose_name='Результат')),
            ],
            options={
                'verbose_name_plural': 'Строки плана мониторинга для непосредственного результата',
                'verbose_name': 'Строка плана мониторинга для непосредственного результата',
            },
        ),
        migrations.CreateModel(
            name='MonitoringPlanLineShortOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Вопрос')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('method', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Метод')),
                ('tool', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Инструмент')),
                ('frequency', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Частота сбора')),
                ('reporting', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Отчетность и использование')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('result_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.ProgramShortOutcome', verbose_name='Результат')),
            ],
            options={
                'verbose_name_plural': 'Строки плана мониторинга для краткосрочного социального результата',
                'verbose_name': 'Строка плана мониторинга для краткосрочного социального результата',
            },
        ),
    ]
