# Generated by Django 2.0.2 on 2020-08-31 04:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0015_auto_20200828_0500'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userrequest',
            old_name='acceptedon',
            new_name='verifiedon',
        ),
        migrations.AlterField(
            model_name='userrequest',
            name='createdon',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2020, 8, 31, 4, 34, 29, 714807), verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
