# Generated by Django 2.0.2 on 2021-05-06 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0020_logicalmodel_result_tree_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='programimpact',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='programmidoutcome',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='programoutput',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
        migrations.AddField(
            model_name='programshortoutcome',
            name='priority',
            field=models.IntegerField(blank=True, default=0, verbose_name='Приоритет'),
        ),
    ]
