# Generated by Django 2.0.2 on 2022-01-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0023_auto_20220120_0011'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringformlineimpact',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringformlinemidoutcome',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringformlineoutput',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringformlineshortoutcome',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringplanlineimpact',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringplanlinemidoutcome',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringplanlineoutput',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
        migrations.AddField(
            model_name='monitoringplanlineshortoutcome',
            name='sort_index',
            field=models.IntegerField(default=0, verbose_name='Индекс сортировки'),
        ),
    ]
