# Generated by Django 2.0.2 on 2022-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0030_outcomelevel'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название элемента системы мониторинга и оценки')),
            ],
            options={
                'verbose_name': 'Элемент системы мониторинга и оценки',
                'verbose_name_plural': 'Элемент системы мониторинга и оценки',
            },
        ),
    ]
