# Generated by Django 2.0.2 on 2022-01-24 01:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0033_auto_20220124_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название инструмента')),
                ('info', models.CharField(max_length=500, verbose_name='Аннотация')),
                ('method_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.Method', verbose_name='Метод')),
                ('outcome_level_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.OutcomeLevel', verbose_name='Уровень социального результата')),
                ('outcome_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.Outcome', verbose_name='Социальный результат')),
                ('practice_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.Practice', verbose_name='Практика')),
                ('target_refs', models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевые группы')),
                ('thematic_group_ref', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематическая группа')),
            ],
            options={
                'verbose_name': 'Инструменты',
                'verbose_name_plural': 'Инструменты',
            },
        ),
    ]
