# Generated by Django 2.0.2 on 2022-01-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0036_auto_20220124_1215'),
    ]

    operations = [
        migrations.AddField(
            model_name='logicalmodel',
            name='thematic_group_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематическая группа'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='thematic_group_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематическая группа'),
        ),
    ]
