# Generated by Django 3.1.5 on 2021-01-15 13:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=255, verbose_name='Имя')),
                ('lname', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(max_length=15, verbose_name='Телефон')),
                ('mail', models.EmailField(max_length=254, verbose_name='Mail')),
                ('msg', models.CharField(max_length=255, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Форма обратной связи',
                'verbose_name_plural': 'Форма обратной связи',
                'db_table': 'user_mail',
            },
        ),
        migrations.CreateModel(
            name='NewsCat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('slug', models.SlugField(unique=True)),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
            options={
                'verbose_name': 'Разделы новостей',
                'verbose_name_plural': 'Разделы новостей',
                'db_table': 'naws_cat',
                'ordering': ['create'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail', models.EmailField(max_length=254, verbose_name='Mail')),
            ],
            options={
                'verbose_name': 'Подписки',
                'verbose_name_plural': 'Подписки',
                'db_table': 'mail_list',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('name', models.CharField(max_length=255, verbose_name='Название страницы')),
                ('title', models.CharField(max_length=255, verbose_name='title в браузере')),
                ('desc', models.CharField(max_length=255, verbose_name='desc в браузере')),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('minitext', models.TextField(null=True, verbose_name='Краткое описание')),
                ('maintext', models.TextField(null=True, verbose_name='Описание')),
                ('active', models.BooleanField(default=True, verbose_name='Активно')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.newscat', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Новости',
                'verbose_name_plural': 'Новости',
                'db_table': 'naws',
                'ordering': ['create'],
            },
        ),
    ]
