# Generated by Django 3.1.5 on 2021-01-15 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscat',
            name='size',
            field=models.CharField(choices=[('normal', 'Нормальный'), ('big', 'Большой'), ('over_big', 'Очень большой')], default='normal', max_length=255, verbose_name='Шрифт'),
        ),
    ]
