# Generated by Django 3.1.5 on 2021-01-16 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_newscat_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainform',
            name='msg',
            field=models.TextField(verbose_name='Сообщение'),
        ),
        migrations.AlterField(
            model_name='news',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Название новости'),
        ),
    ]
