# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 18:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('logo_name', models.CharField(max_length=20)),
                ('text', models.CharField(max_length=200)),
                ('link_to', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Контакты',
                'verbose_name': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='Description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('logo_name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
                ('text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Описания',
                'verbose_name': 'Описание',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('content', models.FileField(upload_to='%Y/%m/%d/')),
            ],
            options={
                'verbose_name_plural': 'Документы страницы материалы',
                'verbose_name': 'Документ страницы материалы',
            },
        ),
        migrations.CreateModel(
            name='SocialNetworkLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('logo_name', models.CharField(max_length=20)),
                ('link_to', models.CharField(max_length=300)),
            ],
            options={
                'verbose_name_plural': 'Ссылки на социальные сети',
                'verbose_name': 'Ссылка на соц.сеть',
            },
        ),
    ]
