# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-27 04:38
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название страницы')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, default=None, null=True, verbose_name='Содержание')),
            ],
            options={
                'verbose_name_plural': 'Страницы',
                'verbose_name': 'Страница',
            },
        ),
    ]
