# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 06:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb', '0002_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetsHyperlink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Текст ссылки')),
                ('url', models.CharField(max_length=200, verbose_name='URL ссылки')),
            ],
            options={
                'verbose_name': 'Ссылки страницы целевых групп',
            },
        ),
    ]
