# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-03-25 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcb', '0003_targetshyperlink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='targetshyperlink',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Текст ссылки'),
        ),
    ]
