# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 18:40
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=700, verbose_name='Деятельность')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Деятельность',
                'verbose_name_plural': 'Деятельности',
            },
        ),
        migrations.CreateModel(
            name='Impact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Социальный эффект',
                'verbose_name_plural': 'Социальные эффекты',
            },
        ),
        migrations.CreateModel(
            name='ImpactIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('plan', models.CharField(blank=True, max_length=500, verbose_name='План')),
                ('fact', models.CharField(blank=True, max_length=500, verbose_name='Факт')),
                ('frequency', models.IntegerField(blank=True, default=None, null=True, verbose_name='Частота сбора')),
                ('owner', models.CharField(blank=True, default='', max_length=1000, verbose_name='Кто ответственен за сбор')),
                ('reports', models.CharField(blank=True, default='', max_length=1000, verbose_name='В каких отчетах используется')),
                ('values', models.CharField(blank=True, default='', max_length=1000, verbose_name='Значения показателя')),
                ('impact_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.Impact')),
            ],
            options={
                'verbose_name': 'Показатель социального эффекта',
                'verbose_name_plural': 'Показатели социального эффекта',
            },
        ),
        migrations.CreateModel(
            name='Outcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Социальный результат',
                'verbose_name_plural': 'Социальные результаты',
            },
        ),
        migrations.CreateModel(
            name='OutcomeIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('plan', models.CharField(blank=True, max_length=500, verbose_name='План')),
                ('fact', models.CharField(blank=True, max_length=500, verbose_name='Факт')),
                ('method', models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных')),
                ('custom_method', models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных')),
                ('frequency', models.IntegerField(blank=True, default=None, null=True, verbose_name='Частота сбора')),
                ('owner', models.CharField(blank=True, default='', max_length=1000, verbose_name='Кто ответственен за сбор')),
                ('reports', models.CharField(blank=True, default='', max_length=1000, verbose_name='В каких отчетах используется')),
                ('values', models.CharField(blank=True, default='', max_length=1000, verbose_name='Значения показателя')),
                ('outcome_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.Outcome')),
            ],
            options={
                'verbose_name': 'Показатель социального результата',
                'verbose_name_plural': 'Показатели социального результата',
            },
        ),
        migrations.CreateModel(
            name='OutcomeIndicatorMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Значение метода сбора данных')),
                ('outcome_indicator_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.OutcomeIndicator')),
            ],
            options={
                'verbose_name': 'Метод показателя социального результата',
                'verbose_name_plural': 'Методы показателя социального результата',
            },
        ),
        migrations.CreateModel(
            name='Output',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
                ('activity_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.Activity', verbose_name='Деятельность')),
            ],
            options={
                'verbose_name': 'Непосредственный результат',
                'verbose_name_plural': 'Непосредственные результаты',
            },
        ),
        migrations.CreateModel(
            name='OutputIndicator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('plan', models.CharField(blank=True, max_length=500, verbose_name='План')),
                ('fact', models.CharField(blank=True, max_length=500, verbose_name='Факт')),
                ('method', models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных')),
                ('custom_method', models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных')),
                ('frequency', models.IntegerField(blank=True, default=None, null=True, verbose_name='Частота сбора')),
                ('owner', models.CharField(blank=True, default='', max_length=1000, verbose_name='Кто ответственен за сбор')),
                ('reports', models.CharField(blank=True, default='', max_length=1000, verbose_name='В каких отчетах используется')),
                ('values', models.CharField(blank=True, default='', max_length=1000, verbose_name='Значения показателя')),
                ('output_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.Output')),
            ],
            options={
                'verbose_name': 'Показатель непосредственного результата',
                'verbose_name_plural': 'Показатели непосредственного результата',
            },
        ),
        migrations.CreateModel(
            name='OutputIndicatorMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(blank=True, max_length=500, verbose_name='Значение метода сбора данных')),
                ('output_indicator_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.OutputIndicator')),
            ],
            options={
                'verbose_name': 'Метод показателя непосредственного результата',
                'verbose_name_plural': 'Методы показателя непосредственного результата',
            },
        ),
        migrations.CreateModel(
            name='PageComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=1000, verbose_name='Комментарий к странице')),
                ('page_url', models.CharField(blank=True, max_length=100, null=True, verbose_name='Страница')),
            ],
            options={
                'verbose_name': 'Комментарий эксперта',
                'verbose_name_plural': 'Комментарии экспертов',
            },
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('subtitle', models.CharField(blank=True, default=None, max_length=100, verbose_name='Группа')),
                ('custom_subtitle', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Либо введите свой вариант группы')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
            ],
            options={
                'verbose_name': 'Ресурс',
                'verbose_name_plural': 'Ресурсы',
            },
        ),
        migrations.CreateModel(
            name='ResultsChain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название программы')),
                ('organization', models.CharField(blank=True, max_length=150, verbose_name='Организация')),
                ('website', models.CharField(blank=True, max_length=80, verbose_name='Сайт')),
                ('formation_date', models.DateField(auto_now_add=True, verbose_name='Дата формирования')),
                ('realization_days', models.IntegerField(blank=True, null=True, verbose_name='Дней на реализацию')),
                ('realization_date', models.DateField(blank=True, default=datetime.date.today, verbose_name='Реализовать до')),
                ('terms', models.CharField(blank=True, max_length=300, null=True, verbose_name='Сроки')),
                ('durability', models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Длительность проектного цикла')),
                ('loop_beginning_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата начала проектного цикла')),
                ('loop_ending_date', models.DateField(blank=True, default=None, null=True, verbose_name='Дата окончания проектного цикла')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name': 'Цепочка результатов',
                'verbose_name_plural': 'Цепочки результатов',
            },
        ),
        migrations.CreateModel(
            name='ResultsChainUserConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rc_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь цепочки и пользователя',
                'verbose_name_plural': 'Связи цепочки и пользователя',
            },
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=500, verbose_name='Выберите из списка')),
                ('custom_value', models.CharField(blank=True, max_length=500, verbose_name='Либо введите свой вариант')),
                ('comm', models.CharField(blank=True, max_length=5000, verbose_name='Комментарий')),
                ('rc_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain')),
            ],
            options={
                'verbose_name': 'Целевая группа',
                'verbose_name_plural': 'Целевые группы',
            },
        ),
        migrations.CreateModel(
            name='TargetsListGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Группа списка "Целевые группы"',
                'verbose_name_plural': 'Группы списка "Целевые группы"',
            },
        ),
        migrations.CreateModel(
            name='TargetsListItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=300, verbose_name='Значение')),
                ('item_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.TargetsListGroup')),
            ],
            options={
                'verbose_name': 'Значение списка "Целевые группы"',
                'verbose_name_plural': 'Значения списка "Целевые группы"',
            },
        ),
        migrations.AddField(
            model_name='resource',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='output',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='output',
            name='target_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.Target', verbose_name='Целевая группа'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='output_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.Output', verbose_name='Непосредственный результат'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='target_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.Target', verbose_name='Целевая группа'),
        ),
        migrations.AddField(
            model_name='impactindicator',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='impact',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
        migrations.AddField(
            model_name='impact',
            name='target_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.Target', verbose_name='Целевая группа'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rc_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.ResultsChain'),
        ),
    ]
