# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-08-28 18:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=300, verbose_name='Название организации')),
                ('company_site', models.CharField(blank=True, default='', max_length=300, verbose_name='Веб-сайт организации')),
                ('company_logo', models.ImageField(blank=True, default=None, null=True, upload_to='', verbose_name='Логотип организации')),
                ('company_owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Создатель')),
            ],
            options={
                'verbose_name_plural': 'Организации',
                'verbose_name': 'Организация',
            },
        ),
        migrations.CreateModel(
            name='CompanyDataUserConnector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_data_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rcapp.CompanyData', verbose_name='Организация')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Участник')),
            ],
        ),
        migrations.AddField(
            model_name='resultschain',
            name='company_data_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.CompanyData', verbose_name='Организация'),
        ),
    ]
