# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-01 14:40
from __future__ import unicode_literals

from django.db import migrations, models
import rcapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0002_auto_20170828_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='company_logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to=rcapp.models.parse_filename, verbose_name='Логотип организации'),
        ),
    ]
