# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0004_auto_20171004_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactindicator',
            name='method_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить файл с методикой'),
        ),
        migrations.AddField(
            model_name='impactindicator',
            name='source_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить форму источника данных'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='method_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить файл с методикой'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='source_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить форму источника данных'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='method_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить файл с методикой'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='source_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Загрузить форму источника данных'),
        ),
    ]
