# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-04 20:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0005_auto_20171004_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='impactindicator',
            name='method_file',
        ),
    ]
