# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 04:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0007_auto_20171004_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactindicator',
            name='methodic',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Методика сбора данных'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='methodic',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Методика сбора данных'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='methodic',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Методика сбора данных'),
        ),
    ]
