# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-05 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0008_auto_20171005_0444'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='contact_email',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='E-mail контактного лица'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='contact_fio',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='ФИО контактного лица'),
        ),
        migrations.AddField(
            model_name='companydata',
            name='contact_job',
            field=models.CharField(blank=True, default=None, max_length=300, null=True, verbose_name='Должность контактного лица'),
        ),
    ]
