# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0011_resultschain_case_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeIndicatorPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=500, verbose_name='План')),
                ('fact', models.CharField(blank=True, max_length=500, verbose_name='Факт')),
                ('year', models.IntegerField(blank=True, default=2017, verbose_name='Год')),
                ('outcome_indicator_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.OutcomeIndicator')),
            ],
        ),
        migrations.CreateModel(
            name='OutputIndicatorPF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, max_length=500, verbose_name='План')),
                ('fact', models.CharField(blank=True, max_length=500, verbose_name='Факт')),
                ('year', models.IntegerField(blank=True, default=2017, verbose_name='Год')),
                ('output_indicator_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='rcapp.OutputIndicator')),
            ],
        ),
    ]
