# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0013_auto_20171119_1638'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeindicator',
            name='outcome_indicator_pf_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.OutcomeIndicatorPF'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='output_indicator_pf_ref',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.OutputIndicatorPF'),
        ),
    ]
