# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0014_auto_20171119_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcomeindicator',
            name='outcome_indicator_pf_ref',
        ),
        migrations.RemoveField(
            model_name='outputindicator',
            name='output_indicator_pf_ref',
        ),
        migrations.AddField(
            model_name='outcomeindicatorpf',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Текущий год'),
        ),
        migrations.AddField(
            model_name='outputindicatorpf',
            name='current',
            field=models.BooleanField(default=True, verbose_name='Текущий год'),
        ),
    ]
