# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0015_auto_20171119_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeindicator',
            name='year',
            field=models.IntegerField(blank=True, default=2017, verbose_name='Год'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='year',
            field=models.IntegerField(blank=True, default=2017, verbose_name='Год'),
        ),
    ]
