# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-19 21:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0016_auto_20171119_2026'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
        migrations.AddField(
            model_name='output',
            name='order',
            field=models.IntegerField(blank=True, default=0, verbose_name='Порядковый номер'),
        ),
    ]
