# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-20 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rcapp', '0018_auto_20171120_0443'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAdditionalData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Организация')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
