# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-23 21:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0019_useradditionaldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultschain',
            name='head_comment',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Ссылка на отзыв куратора'),
        ),
    ]
