# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-25 08:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0021_librarypage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='subtitle',
            field=models.CharField(blank=True, default=None, max_length=100, null=True, verbose_name='Группа'),
        ),
    ]
