# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-06 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0022_auto_20171125_0816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='librarypage',
            options={'verbose_name': 'Страница библиотеки', 'verbose_name_plural': 'Страницы библиотеки'},
        ),
    ]
