# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-18 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0023_auto_20171206_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100, verbose_name='Логин')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('organization', models.CharField(blank=True, max_length=100, verbose_name='Организация')),
                ('occupation', models.CharField(blank=True, max_length=100, verbose_name='Должность')),
                ('password', models.CharField(max_length=100, verbose_name='Пароль')),
                ('password_repeat', models.CharField(max_length=100, verbose_name='Повторите пароль')),
            ],
            options={
                'verbose_name_plural': 'Запросы на регистрацию нового пользователя',
                'verbose_name': 'Запрос на регистрацию нового пользователя',
            },
        ),
    ]
