# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 12:45
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0024_userrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpParagraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название подсказки')),
                ('short_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Краткая подсказка')),
                ('full_content', ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Полная подсказка')),
                ('order', models.IntegerField(blank=True, default=1, verbose_name='Порядковый номер')),
                ('display_full', models.BooleanField(default=True, verbose_name='Отображать в полном руководстве')),
                ('display_short', models.BooleanField(default=True, verbose_name='Отображать во всплывающей подсказке')),
            ],
        ),
    ]
