# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-16 14:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0025_helpparagraph'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='helpparagraph',
            options={'verbose_name': 'Подсказка онлайн-руководства', 'verbose_name_plural': 'Подсказки онлайн-руководства'},
        ),
    ]
