# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-23 18:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0027_userrequest_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpparagraph',
            name='special_name',
            field=models.CharField(default='', max_length=200, verbose_name='Системное название'),
            preserve_default=False,
        ),
    ]
