# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 05:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0029_auto_20180131_0444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impact',
            name='outcome_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.Outcome', verbose_name='Социальный результат'),
        ),
    ]
