# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-01-31 08:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0030_auto_20180131_0512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impactindicator',
            name='recieve_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата первого измерения'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='recieve_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата первого измерения'),
        ),
        migrations.AlterField(
            model_name='outputindicator',
            name='recieve_date',
            field=models.DateField(blank=True, default=None, null=True, verbose_name='Дата первого измерения'),
        ),
    ]
