# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-12 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0031_auto_20180131_0800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='target_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.Target', verbose_name='Целевая группа'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='subtitle',
            field=models.CharField(blank=True, default='Другое', max_length=100, null=True, verbose_name='Группа'),
        ),
    ]
