# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-02-19 04:57
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0032_auto_20180212_0446'),
    ]

    operations = [
        migrations.AddField(
            model_name='helpparagraph',
            name='additional_content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, verbose_name='Дополнение'),
        ),
    ]
