# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0033_helpparagraph_additional_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='organization',
            field=models.CharField(max_length=100, verbose_name='Организация'),
        ),
    ]
