# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-03 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0034_auto_20180303_1801'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='region',
            field=models.CharField(default='-', max_length=100, verbose_name='Регион'),
        ),
    ]
