# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-05 19:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0035_userrequest_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
    ]
