# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 20:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0036_auto_20180305_1931'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='target_ref',
        ),
        migrations.RemoveField(
            model_name='impact',
            name='outcome_ref',
        ),
        migrations.RemoveField(
            model_name='outcome',
            name='output_ref',
        ),
        migrations.RemoveField(
            model_name='output',
            name='activity_ref',
        ),
    ]
