# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-03-10 20:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0038_activity_target_refs'),
    ]

    operations = [
        migrations.AddField(
            model_name='impact',
            name='outcome_refs',
            field=models.ManyToManyField(blank=True, to='rcapp.Outcome', verbose_name='Социальные результаты'),
        ),
        migrations.AddField(
            model_name='outcome',
            name='output_refs',
            field=models.ManyToManyField(blank=True, to='rcapp.Output', verbose_name='Непосредственные результаты'),
        ),
        migrations.AddField(
            model_name='output',
            name='activity_refs',
            field=models.ManyToManyField(blank=True, to='rcapp.Activity', verbose_name='Деятельности'),
        ),
    ]
