# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-05-28 13:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0039_auto_20180310_2052'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='created',
            field=models.BooleanField(default=False, verbose_name='Создан'),
        ),
    ]
