# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 11:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0040_userrequest_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultschain',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Сроки'),
            preserve_default=False,
        ),
    ]
