# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-06-02 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0041_auto_20180602_1121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companydata',
            name='contact_email',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='E-mail контактного лица'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_fio',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='ФИО контактного лица'),
        ),
        migrations.AlterField(
            model_name='companydata',
            name='contact_job',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Должность контактного лица'),
        ),
        migrations.AlterField(
            model_name='resultschain',
            name='terms',
            field=models.CharField(blank=True, default='', max_length=300, verbose_name='Сроки'),
        ),
    ]
