# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-02 14:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0044_auto_20180602_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userrequest',
            name='submission_date',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата подтверждения'),
        ),
    ]
