# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-04 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0045_auto_20180702_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='wanna_be_shown',
            field=models.BooleanField(default=False, verbose_name='После регистрации отобразить на странице пользователей'),
            preserve_default=False,
        ),
    ]
