# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-07-10 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0046_userrequest_wanna_be_shown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='wanna_be_shown',
            field=models.BooleanField(default=True, verbose_name='После регистрации отобразить на странице пользователей'),
        ),
    ]
