# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-20 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0047_auto_20180710_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactindicator',
            name='reports_publicity',
            field=models.CharField(default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='reports_publicity',
            field=models.CharField(default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='reports_publicity',
            field=models.CharField(default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
        migrations.AlterField(
            model_name='impactindicator',
            name='reports',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Отчеты'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='reports',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Отчеты'),
        ),
        migrations.AlterField(
            model_name='outputindicator',
            name='reports',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Отчеты'),
        ),
    ]
