# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-20 09:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0048_auto_20181020_0833'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrequest',
            name='last_seen',
            field=models.DateTimeField(blank=True, default=None, null=True, verbose_name='Дата последнего входа'),
        ),
        migrations.AlterField(
            model_name='impactindicator',
            name='reports_publicity',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='reports_publicity',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
        migrations.AlterField(
            model_name='outputindicator',
            name='reports_publicity',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='В каких отчетах используется'),
        ),
    ]
