# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-20 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0049_auto_20181020_0940'),
    ]

    operations = [
        migrations.AddField(
            model_name='outcomeindicator',
            name='custom_method2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 2'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='custom_method3',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 3'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='method2',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 2'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='method3',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 3'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='custom_method2',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 2'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='custom_method3',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 3'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='method2',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 2'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='method3',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 3'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='custom_method',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 1'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='method',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 1'),
        ),
        migrations.AlterField(
            model_name='outputindicator',
            name='custom_method',
            field=models.CharField(blank=True, max_length=500, verbose_name='Свой метод сбора данных 1'),
        ),
        migrations.AlterField(
            model_name='outputindicator',
            name='method',
            field=models.CharField(default='custom', max_length=500, verbose_name='Метод сбора данных 1'),
        ),
    ]
