# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-10-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0050_auto_20181020_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='impactindicator',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текстовое описание показателя'),
        ),
        migrations.AddField(
            model_name='outcomeindicator',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текстовое описание показателя'),
        ),
        migrations.AddField(
            model_name='outputindicator',
            name='description',
            field=models.CharField(blank=True, max_length=500, verbose_name='Текстовое описание показателя'),
        ),
    ]
