# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2018-11-28 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0055_benchmarkingparametersquery'),
    ]

    operations = [
        migrations.AddField(
            model_name='resultschain',
            name='display_organization',
            field=models.BooleanField(default=False, verbose_name='Отображать организацию'),
        ),
    ]
