# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-02-20 06:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0056_resultschain_display_organization'),
    ]

    operations = [
        migrations.AddField(
            model_name='companydata',
            name='display_in_list',
            field=models.BooleanField(default=True, verbose_name='Отображать в списке'),
        ),
    ]
