# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2019-06-18 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rcapp', '0057_companydata_display_in_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultschain',
            name='company_data_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rcapp.CompanyData', verbose_name='Название организации'),
        ),
        migrations.AlterField(
            model_name='resultschain',
            name='website',
            field=models.CharField(blank=True, max_length=80, verbose_name='Сайт организации'),
        ),
    ]
