# Generated by Django 3.0.8 on 2020-07-19 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_outcomeindicator'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название метода и инструмента сбора данных')),
                ('url', models.CharField(max_length=500, verbose_name='Ссылка на метод и инструмент сбора данных')),
            ],
            options={
                'verbose_name': 'Показатель социального результата',
                'verbose_name_plural': 'Показатели социального результата',
            },
        ),
    ]
