# Generated by Django 3.0.8 on 2020-07-29 04:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0005_auto_20200719_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='user_ref',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название программы')),
                ('description', models.CharField(max_length=2000, verbose_name='Описание программы')),
                ('period', models.CharField(max_length=2000, verbose_name='Сроки программы')),
                ('practice_refs', models.ManyToManyField(blank=True, to='public.Practice', verbose_name='Практики')),
                ('target_refs', models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевые группы')),
                ('user_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программа',
            },
        ),
    ]
