# Generated by Django 2.0.2 on 2020-07-31 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0006_auto_20200729_0440'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='program',
            options={'verbose_name': 'Программа', 'verbose_name_plural': 'Программы'},
        ),
    ]
