# Generated by Django 2.0.2 on 2020-08-11 18:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0007_auto_20200731_0514'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogicalModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название логической модели')),
                ('organization', models.CharField(max_length=500, verbose_name='Организация')),
                ('period', models.CharField(max_length=2000, verbose_name='Сроки реализации')),
                ('verification_info', models.CharField(blank=True, default='', max_length=2000, verbose_name='Сведения о верификации практики, в рамках которой реализовывалась программа')),
                ('verification_level_regularity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Регламентированность практики')),
                ('verification_level_validity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Обоснованность практики')),
                ('verification_level_outcome_accessibility', models.CharField(blank=True, default='', max_length=2000, verbose_name='Достижение социальных результатов')),
                ('verification_level_outcome_validity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Обоснованность данных о социальных результатах')),
                ('model_file', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл логической модели')),
                ('outcome_refs', models.ManyToManyField(blank=True, to='public.Outcome', verbose_name='Социальные результаты')),
                ('practice_refs', models.ManyToManyField(blank=True, to='public.Practice', verbose_name='Практики')),
                ('target_refs', models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевые группы')),
            ],
            options={
                'verbose_name': 'Логическая модель',
                'verbose_name_plural': 'Логические модели',
            },
        ),
        migrations.CreateModel(
            name='LogicalModelLibraryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logical_model_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.LogicalModel', verbose_name='Логическая модель')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь логической модели с личной библиотекой',
                'verbose_name_plural': 'Связи логических моделей с личной библиотекой',
            },
        ),
    ]
