# Generated by Django 2.0.2 on 2020-08-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0008_logicalmodel_logicalmodellibrarylink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст предположения')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Предположения',
                'verbose_name': 'Предположение',
            },
        ),
        migrations.CreateModel(
            name='Context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст контекста')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Контексты',
                'verbose_name': 'Контекст',
            },
        ),
        migrations.AlterField(
            model_name='outcomeexactname',
            name='outcome_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Outcome', verbose_name='Социальный результат'),
        ),
        migrations.AlterField(
            model_name='outcomeindicator',
            name='outcome_ref',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Outcome', verbose_name='Социальный результат'),
        ),
    ]
