# Generated by Django 2.0.2 on 2020-08-12 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0009_auto_20200811_2349'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название активности')),
                ('info', models.TextField(verbose_name='Информация')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('target_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='public.Target', verbose_name='Целевая группа')),
            ],
            options={
                'verbose_name_plural': 'Активности',
                'verbose_name': 'Активность',
            },
        ),
    ]
