# Generated by Django 2.0.2 on 2020-08-26 03:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0013_monitoringplanlineimpact_monitoringplanlinemidoutcome_monitoringplanlineoutput_monitoringplanlinesho'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonitoringFormLineImpact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('plan', models.FloatField(blank=True, default=None, null=True, verbose_name='Плановое значение')),
                ('period1', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact1', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period2', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact2', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period3', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact3', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period4', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact4', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Строки рабочей формы мониторинга социального эффекта',
                'verbose_name': 'Строка рабочей формы мониторинга социального эффекта',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormLineMidOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('plan', models.FloatField(blank=True, default=None, null=True, verbose_name='Плановое значение')),
                ('period1', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact1', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period2', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact2', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period3', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact3', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period4', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact4', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Строки рабочей формы мониторинга среднесрочного социального результата',
                'verbose_name': 'Строка рабочей формы мониторинга среднесрочного социального результата',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormLineOutput',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('plan', models.FloatField(blank=True, default=None, null=True, verbose_name='Плановое значение')),
                ('period1', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact1', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period2', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact2', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period3', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact3', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period4', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact4', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Строки рабочей формы мониторинга непосредственного результата',
                'verbose_name': 'Строка рабочей формы мониторинга непосредственного результата',
            },
        ),
        migrations.CreateModel(
            name='MonitoringFormLineShortOutcome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indicator', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Показатель')),
                ('plan', models.FloatField(blank=True, default=None, null=True, verbose_name='Плановое значение')),
                ('period1', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact1', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period2', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact2', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period3', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact3', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('period4', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Период сбора')),
                ('fact4', models.FloatField(blank=True, default=None, null=True, verbose_name='Фактическое значение')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
            ],
            options={
                'verbose_name_plural': 'Строки рабочей формы мониторинга краткосрочного социального результата',
                'verbose_name': 'Строка рабочей формы мониторинга краткосрочного социального результата',
            },
        ),
    ]
