# Generated by Django 2.0.2 on 2020-08-31 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0016_auto_20200831_0434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrequest',
            name='region',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Регион'),
        ),
    ]
