# Generated by Django 2.0.2 on 2020-09-25 06:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0017_auto_20200831_0454'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('info', models.TextField(blank=True, default=None, null=True, verbose_name='Информация')),
                ('program_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Program', verbose_name='Программа')),
                ('target_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Target', verbose_name='Целевая группа')),
            ],
            options={
                'verbose_name_plural': 'Описания целевых групп',
                'verbose_name': 'Описание целевой группы',
            },
        ),
    ]
