# Generated by Django 2.0.2 on 2020-11-04 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0018_targetdescription'),
    ]

    operations = [
        migrations.AddField(
            model_name='programimpact',
            name='program_mid_outcome_many_refs',
            field=models.ManyToManyField(blank=True, related_name='program_mid_outcome_many_refs', to='public.ProgramMidOutcome', verbose_name='Среднесрочные социальные результаты'),
        ),
        migrations.AddField(
            model_name='programmidoutcome',
            name='program_short_outcome_many_refs',
            field=models.ManyToManyField(blank=True, related_name='program_short_outcome_many_refs', to='public.ProgramShortOutcome', verbose_name='Краткосрочные социальные результаты'),
        ),
        migrations.AddField(
            model_name='programshortoutcome',
            name='program_output_many_refs',
            field=models.ManyToManyField(blank=True, related_name='program_output_many_refs', to='public.ProgramOutput', verbose_name='Непосредственные результаты'),
        ),
    ]
