# Generated by Django 2.0.2 on 2022-01-23 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0025_toolsitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accordance',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='activitiestypes',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='addressee',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='elementsmonitoring',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='method',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='practicetype',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='resultlevel',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='sociallibrarypeon',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='thematicgroup',
            name='subgroup',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='addressee',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='method',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='practice_type',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='publication_status',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='result_level',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='socila_library_pion',
        ),
        migrations.RemoveField(
            model_name='toolsitem',
            name='thematic_group',
        ),
        migrations.DeleteModel(
            name='Accordance',
        ),
        migrations.DeleteModel(
            name='ActivitiesTypes',
        ),
        migrations.DeleteModel(
            name='Addressee',
        ),
        migrations.DeleteModel(
            name='ElementsMonitoring',
        ),
        migrations.DeleteModel(
            name='Method',
        ),
        migrations.DeleteModel(
            name='PracticeType',
        ),
        migrations.DeleteModel(
            name='ResultLevel',
        ),
        migrations.DeleteModel(
            name='SocialLibraryPEON',
        ),
        migrations.DeleteModel(
            name='ThematicGroup',
        ),
    ]
