# Generated by Django 2.0.2 on 2022-01-23 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0026_auto_20220123_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThematicGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название тематической группы')),
            ],
            options={
                'verbose_name': 'Тематическая группа',
                'verbose_name_plural': 'Тематическая группа',
            },
        ),
    ]
