# Generated by Django 2.0.2 on 2022-01-23 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0027_thematicgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='target',
            name='parent_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Target', verbose_name='Родительский раздел'),
        ),
    ]
