# Generated by Django 2.0.2 on 2022-01-24 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0029_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutcomeLevel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название уровня результата')),
            ],
            options={
                'verbose_name_plural': 'Уровень результата',
                'verbose_name': 'Уровень результата',
            },
        ),
    ]
