# Generated by Django 2.0.2 on 2022-01-29 23:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0037_auto_20220124_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='analysismethod',
            options={'verbose_name': 'Метод анализа', 'verbose_name_plural': 'Методы анализа'},
        ),
        migrations.AlterModelOptions(
            name='evaluationreport',
            options={'verbose_name': 'Oтчёт об оценке', 'verbose_name_plural': 'Oтчёты об оценке'},
        ),
        migrations.AlterModelOptions(
            name='evaluationtype',
            options={'verbose_name': 'Вид оценки', 'verbose_name_plural': 'Виды оценки'},
        ),
        migrations.AlterModelOptions(
            name='method',
            options={'verbose_name': 'Метод', 'verbose_name_plural': 'Методы'},
        ),
        migrations.AlterModelOptions(
            name='monitoringelement',
            options={'verbose_name': 'Элемент системы мониторинга и оценки', 'verbose_name_plural': 'Элементы системы мониторинга и оценки'},
        ),
        migrations.AlterModelOptions(
            name='organizationactivity',
            options={'verbose_name': 'Вид деятельности организации', 'verbose_name_plural': 'Виды деятельности организации'},
        ),
        migrations.AlterModelOptions(
            name='outcomelevel',
            options={'verbose_name': 'Уровень результата', 'verbose_name_plural': 'Уровени результата'},
        ),
        migrations.AlterModelOptions(
            name='representationmethod',
            options={'verbose_name': 'Представлене данных в отчете', 'verbose_name_plural': 'Представления данных в отчете'},
        ),
        migrations.AlterModelOptions(
            name='thematicgroup',
            options={'verbose_name': 'Тематическая группа', 'verbose_name_plural': 'Тематические группы'},
        ),
        migrations.RemoveField(
            model_name='evaluationreport',
            name='evaluation_type',
        ),
        migrations.RemoveField(
            model_name='evaluationreport',
            name='representation_refs',
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='case_ref',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='public.Case', verbose_name='Кейс'),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='evaluation_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл отчёта'),
        ),
        migrations.AddField(
            model_name='evaluationreport',
            name='representation_method_refs',
            field=models.ManyToManyField(blank=True, to='public.RepresentationMethod', verbose_name='Методы представления данных в отчете'),
        ),
        migrations.AlterField(
            model_name='analysismethod',
            name='add_public',
            field=models.BooleanField(default=False, verbose_name='Публичный доступ'),
        ),
        migrations.RemoveField(
            model_name='case',
            name='target_refs',
        ),
        migrations.AddField(
            model_name='case',
            name='target_refs',
            field=models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевая группа'),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='analysis_method_refs',
            field=models.ManyToManyField(blank=True, to='public.AnalysisMethod', verbose_name='Методы анализа данных'),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='evaluation_type_ref',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='public.EvaluationType', verbose_name='Вид оценки'),
        ),
        migrations.AlterField(
            model_name='evaluationreport',
            name='outcome_refs',
            field=models.ManyToManyField(blank=True, to='public.Outcome', verbose_name='Социальные результаты'),
        ),
        migrations.AlterField(
            model_name='evaluationtype',
            name='add_public',
            field=models.BooleanField(default=False, verbose_name='Публичный доступ'),
        ),
        migrations.AlterField(
            model_name='method',
            name='add_public',
            field=models.BooleanField(default=False, verbose_name='Публичный доступ'),
        ),
        migrations.AlterField(
            model_name='outcome',
            name='add_public_confirm',
            field=models.BooleanField(default=False, verbose_name='Подтверждение администратором'),
        ),
        migrations.AlterField(
            model_name='representationmethod',
            name='add_public',
            field=models.BooleanField(default=False, verbose_name='Публичный доступ'),
        ),
    ]
