# Generated by Django 2.0.2 on 2022-02-01 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('public', '0041_auto_20220201_1230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название кейса')),
                ('organization', models.CharField(max_length=500, verbose_name='Организация')),
                ('case_file', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл кейса')),
                ('verification_info', models.CharField(blank=True, default='', max_length=2000, verbose_name='Сведения о верификации практики, в рамках которой реализовывалась программа')),
                ('verification_level_regularity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Регламентированность практики')),
                ('verification_level_validity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Обоснованность практики')),
                ('verification_level_outcome_accessibility', models.CharField(blank=True, default='', max_length=2000, verbose_name='Достижение социальных результатов')),
                ('verification_level_outcome_validity', models.CharField(blank=True, default='', max_length=2000, verbose_name='Обоснованность данных о социальных результатах')),
                ('add_public_will', models.BooleanField(default=False, verbose_name='В общую библиотеку')),
                ('add_public_confirm', models.BooleanField(default=False, verbose_name='Подтверждение администратором ')),
                ('createdby', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('monitoring_element_refs', models.ManyToManyField(blank=True, to='public.MonitoringElement', verbose_name='Элементы системы мониторинга и оценки')),
                ('organization_activity_refs', models.ManyToManyField(blank=True, to='public.OrganizationActivity', verbose_name='Виды деятельности')),
                ('practice_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Practice', verbose_name='Практика')),
                ('target_refs', models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевая группа')),
                ('thematic_group_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематическая группа')),
            ],
            options={
                'verbose_name': 'Кейсы',
                'verbose_name_plural': 'Кейсы',
            },
        ),
        migrations.CreateModel(
            name='CaseLibraryLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='public.Case', verbose_name='Кейс')),
                ('user_ref', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Связь кейса с личной библиотекой',
                'verbose_name_plural': 'Связи кейсов с личной библиотекой',
            },
        ),
        migrations.CreateModel(
            name='EvaluationReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=500, verbose_name='Тип отчета')),
                ('key_questions', models.CharField(max_length=2000, verbose_name='Ключевые вопросы')),
                ('other_results', models.CharField(max_length=2000, verbose_name='Другие результаты')),
                ('evaluation_file', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл отчёта')),
                ('analysis_method_refs', models.ManyToManyField(blank=True, to='public.AnalysisMethod', verbose_name='Методы анализа данных')),
                ('case_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Case', verbose_name='Кейс')),
                ('evaluation_type_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.EvaluationType', verbose_name='Вид оценки')),
                ('method_refs', models.ManyToManyField(blank=True, to='public.Method', verbose_name='Методы')),
                ('outcome_refs', models.ManyToManyField(blank=True, to='public.Outcome', verbose_name='Социальные результаты')),
                ('representation_method_refs', models.ManyToManyField(blank=True, to='public.RepresentationMethod', verbose_name='Методы представления данных в отчете')),
            ],
            options={
                'verbose_name': 'Oтчёт об оценке',
                'verbose_name_plural': 'Oтчёты об оценке',
            },
        ),
    ]
