# Generated by Django 2.0.2 on 2022-02-01 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0043_auto_20220201_1426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tool',
            name='outcome_ref',
        ),
        migrations.AddField(
            model_name='tool',
            name='outcome_refs',
            field=models.ManyToManyField(blank=True, to='public.Outcome', verbose_name='Социальные результаты'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл инструмента'),
        ),
    ]
