# Generated by Django 2.0.2 on 2022-02-04 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0044_auto_20220201_1431'),
    ]

    operations = [
        migrations.AddField(
            model_name='tool',
            name='url',
            field=models.CharField(blank=True, max_length=500, verbose_name='Ссылка на инструмент'),
        ),
    ]
