# Generated by Django 2.0.2 on 2022-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0045_tool_url'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='representationmethod',
            options={'verbose_name': 'Представление данных в отчете', 'verbose_name_plural': 'Представления данных в отчете'},
        ),
        migrations.AlterModelOptions(
            name='tool',
            options={'verbose_name': 'Инструмент', 'verbose_name_plural': 'Инструменты'},
        ),
        migrations.AddField(
            model_name='case',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Ссылка на кейс'),
        ),
        migrations.AlterField(
            model_name='tool',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=500, verbose_name='Ссылка на инструмент'),
        ),
    ]
