# Generated by Django 2.0.2 on 2022-02-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0046_auto_20220205_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitoringplanlineimpact',
            name='tool_type',
            field=models.CharField(choices=[('Tools', 'Библиотека инструментов ПИОН'), ('OutcomeMethods', 'Сторонний инструмент')], default='OutcomeMethods', max_length=100, verbose_name='Откуда инструмент'),
        ),
        migrations.AddField(
            model_name='monitoringplanlinemidoutcome',
            name='tool_type',
            field=models.CharField(choices=[('Tools', 'Библиотека инструментов ПИОН'), ('OutcomeMethods', 'Сторонний инструмент')], default='OutcomeMethods', max_length=100, verbose_name='Откуда инструмент'),
        ),
        migrations.AddField(
            model_name='monitoringplanlineoutput',
            name='tool_type',
            field=models.CharField(choices=[('Tools', 'Библиотека инструментов ПИОН'), ('OutcomeMethods', 'Сторонний инструмент')], default='OutcomeMethods', max_length=100, verbose_name='Откуда инструмент'),
        ),
        migrations.AddField(
            model_name='monitoringplanlineshortoutcome',
            name='tool_type',
            field=models.CharField(choices=[('Tools', 'Библиотека инструментов ПИОН'), ('OutcomeMethods', 'Сторонний инструмент')], default='OutcomeMethods', max_length=100, verbose_name='Откуда инструмент'),
        ),
    ]
