# Generated by Django 2.0.2 on 2022-02-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0047_auto_20220205_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500, verbose_name='Название тега')),
            ],
            options={
                'verbose_name': 'Тег краткой информации инструмента',
                'verbose_name_plural': 'Теги краткой информации инструмента',
            },
        ),
        migrations.AddField(
            model_name='method',
            name='info',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True, verbose_name='Подсказка'),
        ),
        migrations.AddField(
            model_name='tool',
            name='tool_tag_refs',
            field=models.ManyToManyField(blank=True, to='public.ToolTag', verbose_name='Теги краткой информации'),
        ),
    ]
