# Generated by Django 2.0.2 on 2022-02-16 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0048_auto_20220216_1043'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evaluationreport',
            options={'verbose_name': 'Отчёт об оценке', 'verbose_name_plural': 'Отчёты об оценке'},
        ),
    ]
