# Generated by Django 2.0.2 on 2022-02-17 23:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0049_auto_20220216_1149'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToolChangeRequest',
            fields=[
                ('name', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Название инструмента')),
                ('info', models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Аннотация')),
                ('tool_file', models.FileField(blank=True, default=None, null=True, upload_to='', verbose_name='Файл инструмента')),
                ('url', models.CharField(blank=True, default=None, max_length=500, verbose_name='Ссылка на инструмент')),
                ('tool_ref', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='public.Tool')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('add_public_confirm', models.BooleanField(default=False, verbose_name='Принять изменения')),
                ('method_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Method', verbose_name='Метод')),
                ('outcome_level_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.OutcomeLevel', verbose_name='Уровень социального результата')),
                ('outcome_refs', models.ManyToManyField(blank=True, to='public.Outcome', verbose_name='Социальные результаты')),
                ('practice_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.Practice', verbose_name='Практика')),
                ('target_refs', models.ManyToManyField(blank=True, to='public.Target', verbose_name='Целевые группы')),
                ('thematic_group_ref', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематическая группа')),
                ('tool_tag_refs', models.ManyToManyField(blank=True, to='public.ToolTag', verbose_name='Теги краткой информации')),
            ],
            options={
                'verbose_name': 'Запрос на изменение инструмента',
                'verbose_name_plural': 'Запросы на изменение инструментов',
            },
        ),
    ]
