# Generated by Django 2.0.2 on 2022-02-17 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0050_toolchangerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolchangerequest',
            name='outcome_refs',
            field=models.ManyToManyField(blank=True, default=None, to='public.Outcome', verbose_name='Социальные результаты'),
        ),
        migrations.AlterField(
            model_name='toolchangerequest',
            name='target_refs',
            field=models.ManyToManyField(blank=True, default=None, to='public.Target', verbose_name='Целевые группы'),
        ),
        migrations.AlterField(
            model_name='toolchangerequest',
            name='tool_tag_refs',
            field=models.ManyToManyField(blank=True, default=None, to='public.ToolTag', verbose_name='Теги краткой информации'),
        ),
    ]
