# Generated by Django 2.0.2 on 2022-02-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0051_auto_20220217_2341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toolchangerequest',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='toolchangerequest',
            name='url',
            field=models.CharField(blank=True, default=None, max_length=500, null=True, verbose_name='Ссылка на инструмент'),
        ),
    ]
