# Generated by Django 2.0.2 on 2022-02-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0052_auto_20220218_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='method',
            name='info',
            field=models.CharField(blank=True, default='', max_length=1000, verbose_name='Подсказка'),
        ),
    ]
