# Generated by Django 2.0.2 on 2022-03-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0055_auto_20220221_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='thematic_group_ref',
        ),
        migrations.AddField(
            model_name='outcome',
            name='thematic_group_refs',
            field=models.ManyToManyField(blank=True, to='public.ThematicGroup', verbose_name='Тематические группы'),
        ),
    ]
