# Generated by Django 2.0.2 on 2022-03-07 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0056_auto_20220307_1553'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='thematic_group_refs',
        ),
        migrations.AddField(
            model_name='outcome',
            name='thematic_group_ref',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='public.ThematicGroup', verbose_name='Тематические группы'),
        ),
    ]
