# Generated by Django 2.0.2 on 2022-03-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0057_auto_20220307_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outcome',
            name='thematic_group_ref',
        ),
        migrations.AddField(
            model_name='outcome',
            name='thematic_group_refs',
            field=models.ManyToManyField(blank=True, default=None, to='public.ThematicGroup', verbose_name='Тематические группы'),
        ),
    ]
